### ISSUE TITLE
Ability to push to a subset of the listed managed servers

### ISSUE THREAD

**Issue by cleung2010** [Cimpress-MCP/vagrant-orchestrate#38]
Provide a similar functionality to that of native vagrant, where `up` and `provision` commands can take in a regex expression to only apply those commands to the matching machines. 

`vagrant orchestrate push \dev\` to push to all dev machines, for example, would provide more fine-grained control of what subset of machines to provision.

**Comment by maclennann** [comment]
This already works - vorch just passes it through to vagrant. Though it's slashes for the regex, not backslashes.

Are you seeing some other behavior?

**Comment by cleung2010** [comment]
Cool!
