### ISSUE TITLE
Know which branch vorch is executing under from within the Vagrantfile

### ISSUE THREAD

**Issue by maclennann** [Cimpress-MCP/vagrant-orchestrate#7]
If using `--environments`, I would like to be able to know which environment vorch has determined that I am in so I can use it elsewhere in the Vagrantfile. Specifically, I would like to be able to do something like:

```ruby
config.ssh.private_key_path = "secrets/#{environment}/[keyname]
```

and

```ruby
puppet.options = "--environment #{environment}"
```

**Comment by chrisbaldauf** [comment]
I've added the VAGRANT_ORCHESTRATE_GIT_BRANCH environment variable in version 0.3.1, which should allow you to make sure you're reading the same branch as vagrant orchestrate is.
